# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 10, 15, 22, 156827, tzinfo=utc)),
        ),
    ]
